<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BeMusicSeeker.Updater</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>14.0</LangVersion>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <OptimizationPreference>Size</OptimizationPreference>
  </PropertyGroup>
</Project>
